apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glm53.fullname" . }}-serve
  labels:
    {{- include "glm53.labels" . | nindent 4 }}
data:
  serve.sh: |-
{{ .Files.Get "files/serve.sh" | indent 4 }}
  wait-for-worker.sh: |-
{{ .Files.Get "files/wait-for-worker.sh" | indent 4 }}