{{- if and (not .Values.auth.existingSecret) (or .Values.auth.apiKey .Values.auth.apiKeys) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glm53.authSecretName" . }}
  labels:
    {{- include "glm53.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ concat (ternary (list .Values.auth.apiKey) (list) (ne .Values.auth.apiKey "")) .Values.auth.apiKeys | join " " | quote }}
{{- end }}