apiVersion: v1
kind: Service
metadata:
  name: {{ include "glm53.fullname" . }}
  labels:
    {{- include "glm53.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "glm53.selectorLabels" (dict "root" . "component" "leader") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http